# Generated by Django 5.1.3 on 2024-11-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0002_rename_g_date_graduatingstudents_graduate_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduatingstudents',
            old_name='graduate_date',
            new_name='graduation_date',
        ),
    ]
