# Generated by Django 5.1.3 on 2024-11-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0003_rename_graduate_date_graduatingstudents_graduation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatingstudents',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
