# Generated by Django 5.1.3 on 2024-11-28 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0005_category_alter_graduatingstudents_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatingstudents',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graduates.category'),
        ),
    ]
