# Generated by Django 5.1.3 on 2024-11-28 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0006_graduatingstudents_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatingstudents',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='graduates.category'),
        ),
    ]
